FROM node:argon

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app
RUN npm install

WORKDIR /usr/src/app/examples/chat
RUN npm install

EXPOSE 3000
CMD [ "node", "." ]
